# H2
spring.h2.console:
  enabled: true
  path: /h2

# Datasource
spring.datasource:
  url: jdbc:h2:file:~/animal-shelter
  username: sa
  password:
  driver: class-name=org.h2.Driver

spring.jackson:
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false